version: 2

jobs:
  build:

    environment:
      GITHUB_ORG: https://github.com/angular-schule
      GITHUB_NAME: The Buildbot
      GITHUB_EMAIL: buildbot@angular2buch.de
      NAME: angular-cli-ghpages

    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
      - run: cd src && npm i --silent
      - save_cache:
          key: dependency-cache-{{ checksum "src/package.json" }}
          paths:
            - src/node_modules
      - run: cd src && npm run build
      - run: cd src && npm run test
      - run: cd src/dist && sudo npm link

      - run: sudo npm install -g @angular/cli@next
      - run: ng new your-angular-project --defaults
      - run: cd new your-angular-project && npm link angular-cli-ghpages
      - run: cd new your-angular-project && ng add angular-cli-ghpages
      - run: cd new your-angular-project && ng deploy --repo="$GITHUB_ORG/$NAME.git" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" --cname=angular-cli-ghpages.angular.schule
