version: 2

jobs:
  build:

    environment:
      GITHUB_ORG: https://GH_TOKEN@github.com/angular-schule
      GITHUB_NAME: The Buildbot
      GITHUB_EMAIL: buildbot@angular2buch.de
      NAME: angular-cli-ghpages

    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout


      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "mini-testdrive/package.json" }}
      - run: npm i --silent
      - run: cd mini-testdrive && npm i --silent
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "mini-testdrive/package.json" }}
          paths:
            - node_modules
            - mini-testdrive/node_modules


      - run: cd mini-testdrive && npm run build
      - run: chmod +x bin/angular-cli-ghpages
      - run: cd mini-testdrive && ../angular-cli-ghpages --repo "$GITHUB_ORG/$NAME.git" --name "$GITHUB_NAME" --email "$GITHUB_EMAIL" --dir=dist/mini-testdrive --cname=angular-cli-ghpages.angular.schule

    branches:
      only:
        - XXX-disable-build-for-now-XXX
